/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        RentalAgency agency = new RentalAgency();

        // Add vehicles
        agency.addVehicle(new Car("C1", "Ferrari", 50.0, true));
        agency.addVehicle(new Car("C2", "Buggati", 45.0, false));
        agency.addVehicle(new Motocycle("m1", "Yahama", 44));
        agency.addVehicle(new Truck("t1", "hyundai", 94));

        // View vehicles
        agency.viewVehicles();

        // Rent a vehicle
        Customer customer1 = new Customer("Francis", 20);
        Customer customer2 = new Customer("Fifi" , 60);
        Customer customer3 = new Customer("Vera" , 31);

        agency.rentVehicle("C1", customer1, 3);
        agency.rentVehicle("m1", customer2, 5);
        agency.rentVehicle("t1", customer3, 7);



        // View transactions
        agency.viewTransactions();

        // Return a vehicle
        agency.returnVehicle("TX-1");

        // View transactions again
        agency.viewTransactions();
    }
}
